spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot2cruddemo?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root

  #静态资源访问路径
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static

